### ISSUE TITLE
[Epic] 페이지 구현

### ISSUE THREAD

**Issue by ohamin26** [ohamin26/hair-salon-booking-site-front#6]
에픽 내용

퍼블리싱

- [x] 헤어샵 상세 페이지
- [ ] 디자이너 상세 페이지
- [ ] 마이 페이지
- [ ] 디자이너 전체 페이지
- [ ] 헤어샵 전체 페이지

페이지

- [ ] 헤어샵 상세 페이지
- [ ] 디자이너 상세 페이지
- [ ] 마이 페이지
- [ ] 디자이너 전체 페이지
- [ ] 헤어샵 전체 페이지

예상 기간
-

관련 사항
- 빠지거나 이상한 부분 있으면 추가해주세요..ㅎㅎ
